# Generated by Django 5.0.3 on 2024-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediafield',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
